### ISSUE TITLE
'AWSHTTPSConnection' object has no attribute 'ssl_context'

### ISSUE THREAD

**Issue by daradib** [NYAG/dockers#6]
Reported by @NYAGJW 

    $ aws redshift describe-clusters
    'AWSHTTPSConnection' object has no attribute 'ssl_context'

Seems like boto/botocore#1258 and [Debian bug #854382](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854382).

boto/botocore#1259 has a patch to `/usr/lib/python3/dist-packages/botocore/awsrequest.py`. @NYAGJW  can you test?

**Comment by NYAGJW** [comment]
Yes looks like that will work.  Still trying to find appropriate test case but can't find anything that doesn't need aws credentials.
